version: "3"

services:
    be:
        container_name: klinik-pintar-be
        build:
            context: .
            dockerfile: BE-Dockerfile
        ports:
            - "5000:5000"
        env_file:
            - BE/.env
        command: node BE/index.js
    fe:
        container_name: klinik-pintar-fe
        build:
            context: .
            dockerfile: FE-Dockerfile
        ports:
            - "5173:5173"
            - "5174:5174"
        command: npm run host